image: jekyll/builder:latest

pipelines:
  default:
    - step:
        script:
          - gem install "jekyll-theme-cayman"
          - gem install jekyll-sitemap
          - gem install jekyll-relative-links
          - cd source
          - rm -rf _site
          - jekyll build
          - rm -r .jekyll-cache/
          - git add _site/*
          - git commit -a -m "[skip ci] updated website using pipeline"
          - git push
          - git status
