name: Build deps and MUQ

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


# Concurrency group: which jobs run together and which cancel each other
concurrency:
  group: ${{ github.event.repository.name }}-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: True

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true # true -> cancel all jobs if any fails

      matrix:
        os: [ubuntu-latest, macos-14]
        config:
          - { cc: gcc, cxx: g++, python-version: "3.10" }

    env: # environment variables available to all steps
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
      APT_PACKAGES: python3 pip python-is-python3 g++
      TPL_WORK_DIR: /home/runner/work/tpls_workdir
      MUQ_HOME: /home/runner/work/MIT-MUQ/MIT-MUQ
      MUQ_BUILD_DIR: /home/runner/work/muq_build
      MUQ_INSTALL_DIR: /home/runner/work/muq_install

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --install-suggests $APT_PACKAGES

      - name: Install CMake
        run: |
          export CMAKE_KEYRING=/usr/share/keyrings/kitware-archive-keyring.gpg
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null \
            | gpg --dearmor - \
            | sudo tee $CMAKE_KEYRING >/dev/null
          echo "deb [signed-by=$CMAKE_KEYRING] https://apt.kitware.com/ubuntu/ focal main" \
            | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
          sudo apt-get update
          rm $CMAKE_KEYRING
          sudo apt-get install -y kitware-archive-keyring cmake

      - name: Check environment
        run: |
          echo ======================================================
          echo $(which $CXX) --version
          $CXX --version
          echo ======================================================
          echo $(which cmake) --version
          cmake --version
          echo ======================================================
          echo $(which python) --version
          python --version
          echo ======================================================
          echo Source directory: $MUQ_HOME
          echo TPLs workdir: $TPL_WORK_DIR
          echo ======================================================
          git --version
          cd $MUQ_HOME
          git status

      - name: Build TPLs
        run: |
          cd $MUQ_HOME
          python SupportScripts/build_tpls.py --wdir $TPL_WORK_DIR --with all

      - name: Build MUQ
        run: |
          cd $MUQ_HOME
          cmake -DCMAKE_CXX_COMPILER=$CXX \
          -S $MUQ_HOME -B $MUQ_BUILD_DIR \
          -DCMAKE_INSTALL_PREFIX=$MUQ_INSTALL_DIR \
          -C $TPL_WORK_DIR/tpls_cache.txt \
          -DMUQ_USE_GTEST=ON
          cd $MUQ_BUILD_DIR
          make -j4

      - name: Run Tests
        run: |
          cd $MUQ_BUILD_DIR
          ./RunAllTests