name: Build deps and MUQ

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


# Concurrency group: which jobs run together and which cancel each other
concurrency:
  group: ${{ github.event.repository.name }}-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: True

jobs:
  test:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: true # true -> cancel all jobs if any fails

      matrix:
        mpi: ['openmpi']
        config:
          - { os: ubuntu-latest, cc: gcc, cxx: g++, python-version: "3.10" }
          - { os: macsos-14, cc: gcc-12, cxx: g++-12, python-version: "3.10" }
          - { os: macsos-14, cc: clang, cxx: clang++, python-version: "3.10" }

    env: # environment variables available to all steps
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
      MUQ_HOME: ${{ github.workspace }}
      MUQ_BUILD_DIR: ${{ github.workspace }}/../muq_build
      MUQ_INSTALL_DIR: ${{ github.workspace }}/../muq_install
      TPL_WORK_DIR: ${{ github.workspace }}/../tpls_workdir

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install packages
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y --install-suggests python3 pip python-is-python3 g++

      - name: Install CMake
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          export CMAKE_KEYRING=/usr/share/keyrings/kitware-archive-keyring.gpg
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null \
            | gpg --dearmor - \
            | sudo tee $CMAKE_KEYRING >/dev/null
          echo "deb [signed-by=$CMAKE_KEYRING] https://apt.kitware.com/ubuntu/ focal main" \
            | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
          sudo apt-get update
          rm $CMAKE_KEYRING
          sudo apt-get install -y kitware-archive-keyring cmake

      - name: Setup MPI
        if: matrix.config.os == 'ubuntu-latest'
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}

      - name: Check environment
        run: |
          echo ======================================================
          echo $(which $CXX) --version
          $CXX --version
          echo ======================================================
          echo $(which cmake) --version
          cmake --version
          echo ======================================================
          echo $(which python) --version
          python --version
          echo ======================================================
          echo Source directory: $MUQ_HOME
          echo TPLs workdir: $TPL_WORK_DIR
          echo ======================================================
          git --version
          echo $MUQ_HOME
          cd $MUQ_HOME
          git status

      - name: Build TPLs
        run: |
          cd $MUQ_HOME
          python SupportScripts/build_tpls.py --wdir $TPL_WORK_DIR --with all

      - name: Build and Test MUQ (serial)
        if: matrix.config.os == 'macos-14'
        run: |
          cd $MUQ_HOME
          cmake -DCMAKE_C_COMPILER=$CC \
                -DCMAKE_CXX_COMPILER=$CXX \
                -S $MUQ_HOME -B $MUQ_BUILD_DIR \
                -DCMAKE_INSTALL_PREFIX=$MUQ_INSTALL_DIR \
                -C $TPL_WORK_DIR/tpls_cache.txt \
                -DMUQ_USE_GTEST=ON
          cd $MUQ_BUILD_DIR
          make -j4
          ./RunAllTests

      - name: Build MUQ (mpi)
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          cd $MUQ_HOME
          rm -rf $MUQ_BUILD_DIR
          cmake -DCMAKE_C_COMPILER=mpicc \
                -DCMAKE_CXX_COMPILER=mpic++ \
                -S $MUQ_HOME -B $MUQ_BUILD_DIR \
                -DCMAKE_INSTALL_PREFIX=$MUQ_INSTALL_DIR \
                -C $TPL_WORK_DIR/tpls_cache.txt \
                -DMUQ_USE_GTEST=ON -DMUQ_USE_MPI=ON
          cd $MUQ_BUILD_DIR
          make -j4

      - name: Run Tests (serial)
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          cd $MUQ_BUILD_DIR
          ./RunAllTests

      - name: Run Tests (mpi)
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          cd $MUQ_BUILD_DIR
          mpirun -n 2 ./RunAllParallelTests
