name: Build deps and MUQ

on:
  push:
    branches: [master, testci]
  pull_request:
    branches: [master, testci]


# Concurrency group: which jobs run together and which cancel each other
concurrency:
  group: ${{ github.event.repository.name }}-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: True

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true # true -> cancel all jobs if any fails

      matrix:
        config:
          - { cxx: g++, python-version: "3.10" }

    env: # environment variables available to all steps
      CXX: ${{ matrix.config.cxx }}
      APT_PACKAGES: python3 pip python-is-python3 g++
      TPL_WORK_DIR: /home/runner/work/build/tpls_workdir
      MUQ_HOME: /home/runner/work/MIT-MUQ/MIT-MUQ

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --install-suggests $APT_PACKAGES

      - name: Install CMake
        run: |
          export CMAKE_KEYRING=/usr/share/keyrings/kitware-archive-keyring.gpg
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null \
            | gpg --dearmor - \
            | sudo tee $CMAKE_KEYRING >/dev/null
          echo "deb [signed-by=$CMAKE_KEYRING] https://apt.kitware.com/ubuntu/ focal main" \
            | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
          sudo apt-get update
          rm $CMAKE_KEYRING
          sudo apt-get install -y kitware-archive-keyring cmake

      - name: Check environment
        run: |
          echo ======================================================
          echo $(which $CXX) --version
          $CXX --version
          echo ======================================================
          echo $(which cmake) --version
          cmake --version
          echo ======================================================
          echo $(which python) --version
          python --version
          echo ======================================================
          echo Source directory: $MUQ_HOME
          echo TPLs workdir: $TPL_WORK_DIR
          echo ======================================================
          git --version
          cd $MUQ_HOME
          git status

      - name: Build TPLs
        run: |
          cd $MUQ_HOME
	  python SupportScripts/build_tpls.py --wdir $TPL_WORK_DIR --with-hdf5
